import Head from "next/head";
import Layout from "@/components/layout/Layout";
import { AppProps } from "next/app";
export default function Home({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Aingaran Thirunadarajah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>{Component && <Component {...pageProps} />}</Layout>
      </main>
    </>
  );
}
