import Profile from "@/components/Profile";
import ProfileImage from "@/components/ProfileImage";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Aingaran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="container  mx-auto my-2 text-center">
       
 <ProfileImage />
        
        </div>

      </main>
    </>
  );
}
